name: project1-FYS-STK4155
channels:
  - conda-forge
  - defaults
dependencies:
  - python>3.6
  - notebook>5.2
  - jupyter_dashboards
  - jupyter_dashboards_bundlers
  - matplotlib
  - ipywidgets=7
  - numpy
  - scikit-learn
  - mpl_toolkits
  - random
  - math
  - jupyter_nbextentions_configurator
