#!/usr/bin/env bash

jupyter contrib nbextension install --user
jupyter nbextension enable --py widgetsnbextension
jupyter nbextension enable python-markdown/main
jupyter nbextensions_configurator enable --user
jupyter nbextension enable codefolding/main
jupyter nbextension enable toc2/main
jupyter nbextension enable latex_envs/latex_envs



# Notebooks w/ extensions that auto-run code must be "trusted" to work the first time
jupyter trust *.ipynb
